### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by aoko-sys** [Jeaninezpp/COMVSC#1]
作者您好！
我在研读您这篇论文，我想跑一下您这篇论文的代码，
不知道您是否可以把您这篇论文所用到的数据集都分享给我？email：1064435762@qq.com
祝：
研究快乐，身体健康！

**Comment by Jeaninezpp** [comment]
您好！
在我另外仓库中有分享连接：
https://github.com/Jeaninezpp/multi-view-datasets

**Comment by aoko-sys** [comment]
这个百度网盘里面是完整的多视图数据吗？您没有对它做缺失视图处理吧？


***@***.***
 
发件人： Jeaninezpp
发送时间： 2021-03-17 19:37
收件人： Jeaninezpp/COMVSC
抄送： aoko-sys; Author
主题： Re: [Jeaninezpp/COMVSC] 数据集 (#1)
您好！
在我另外仓库中有分享连接：
https://github.com/Jeaninezpp/multi-view-datasets

**Comment by Jeaninezpp** [comment]
是完整的，没有做缺失处理。

aoko-sys ***@***.***> 于2021年3月17日周三 下午7:40写道：
